### ISSUE TITLE
UnresolvedDependencies

### ISSUE THREAD

**Issue by zabieru96** [acesinc/json-data-generator#3]
When trying to build with "mvn clean package" i get errors as follows
![image](https://cloud.githubusercontent.com/assets/10691031/14300998/d265c372-fb59-11e5-9980-e84a27a9bed5.png)

**Comment by andrewserff** [comment]
Interesting...org.hyperic.sigar is not a dependency of json-data-generator directly, so it is a transient dependency of something we use.  I did find that it exists in the JBoss nexus repo which is why I don't have problems building (we have our own Nexus repo which proxies the jboss repo as well).  You can find it here:

http://repository.jboss.org/nexus/content/groups/public-jboss/org/hyperic/sigar/1.6.5.132/

After looking at the dependency tree by running:
`mvn dependency:tree`
It looks like that dependency is coming from the Tranquility Driver:
```
[INFO] +- com.metamx:tranquility_2.10:jar:0.4.2:compile
[INFO] |  +- org.scala-lang:scala-library:jar:2.10.4:compile
[INFO] |  +- com.metamx:scala-util_2.10:jar:1.9.2:compile
[INFO] |  |  +- org.eintr.loglady:loglady_2.10:jar:1.1.0:compile
[INFO] |  |  +- com.metamx:http-client:jar:1.0.0:compile
[INFO] |  |  +- com.metamx:emitter:jar:0.3.0:compile
[INFO] |  |  +- com.metamx:server-metrics:jar:0.0.10:compile
[INFO] |  |  |  \- org.hyperic:sigar:jar:1.6.5.132:compile
[INFO] |  |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  +- org.joda:joda-convert:jar:1.6:compile
[INFO] |  |  +- com.metamx:time_2.10:jar:0.6-mmx3:compile
[INFO] |  |  +- org.skife.config:config-magic:jar:0.9:compile
[INFO] |  |  +- org.yaml:snakeyaml:jar:1.11:compile
[INFO] |  |  +- org.jdbi:jdbi:jar:2.27:compile
[INFO] |  |  +- mysql:mysql-connector-java:jar:5.1.18:compile
[INFO] |  |  +- com.h2database:h2:jar:1.3.158:compile
[INFO] |  |  +- c3p0:c3p0:jar:0.9.1.2:compile
[INFO] |  |  +- org.apache.zookeeper:zookeeper:jar:3.4.5:compile
[INFO] |  |  |  \- jline:jline:jar:0.9.94:compile
[INFO] |  |  +- org.apache.curator:curator-framework:jar:2.6.0:compile
[INFO] |  |  |  \- org.apache.curator:curator-client:jar:2.6.0:compile
[INFO] |  |  +- org.apache.curator:curator-recipes:jar:2.6.0:compile
[INFO] |  |  \- org.apache.curator:curator-x-discovery:jar:2.6.0:compile
```

I'll see if I can find out if this is something new they added or if they know they are using non-public dependencies.  

So for now, you could either install that dependency locally or add the jboss repository to your pom file so that it can be resolved.

**Comment by zabieru96** [comment]
Okay thanks alot, i sent a pull request with the fix

**Comment by andrewserff** [comment]
I just pushed a fix for this. After talking with the Tranqulity developers, the org.hyperic.sigar dependency is optional (see [here](https://github.com/metamx/server-metrics/blob/master/pom.xml#L74)) and we don't need it. So I've excluded it in our POM file instead of including the jboss repos. Thanks again for pointing this out!
